### ISSUE TITLE
Validator out of memory with stock config

### ISSUE THREAD

**Issue by n0izn0iz** [holaplex/kubes#3]
My validator node is dying due to too much memory used

```
 Warning  Evicted              2m45s  kubelet            The node was low on resource: memory. Container validator was using 126332792Ki, which exceeds its request of 64Gi. Container watchtower was using 9472Ki, which exceeds its request of 0.
  Normal   Killing              2m45s  kubelet            Stopping container watchtower
  Normal   Killing              2m45s  kubelet            Stopping container validator
  Warning  ExceededGracePeriod  2m35s  kubelet            Container runtime did not kill the pod within specified grace period.
```

I'm using the stock `validator/mainnet/deploy.yaml`

The `/etc/rancher/k3s/config.yaml` is 
```yaml
kubelet-arg:
  - "kube-reserved=cpu=500m,memory=1Gi,ephemeral-storage=2Gi"
  - "system-reserved=cpu=500m, memory=1Gi,ephemeral-storage=2Gi"
  - "eviction-hard=memory.available<500Mi,nodefs.available<10%"
```

`lsmem` shows
`Total online memory:     130G`

Swap is correctly set
`cat /proc/meminfo | grep Swap`
```
SwapCached:       217248 kB
SwapTotal:      138406904 kB
SwapFree:       137238520 kB
```

**Comment by mpwsh** [comment]
Yup all looks good.
Can you run `free -h` and `kubectl top pods -n mainnet-solana` and monitor that? Could it be that your node is going out of ram?.  

In my last test  setup i had to spin up a 256 GB ram node in order to make it work.

Also try changing the `validator` deploy limits to a higher value if you have more ram in your node.

```bash
kubectl edit deploy/validator -n mainnet-solana
```
Change `limits` to higher value ([these lines](https://github.com/holaplex/kubes/blob/dev/validator/mainnet/deploy.yaml#L53-L55))

Save and exit

**Comment by n0izn0iz** [comment]
yes, my node is going out of RAM, I have only a 128GB node, I'll try to get a 256GB but it's very expensive, can't I tell solana to use less memory?

**Comment by mpwsh** [comment]
yeah, i feel you, running a validator is super expensive.
You can try raising your SWAP to 256GB as well. Recreate the swapfile, maybe that helps.
Also `accounts-storage` is set to Memory, so the validator can keep up without issue.
You could also change this to an SSD instead of memory to free up some resources as well.

You'll need to create a new PVC for the `accounts-storage`

Open your text editor and create `accounts-pvc.yaml` with:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accounts-storage-pvc
  labels:
    app: validator
spec:
 storageClassName: ""
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
      storage: 300Gi
---
```

And then change [these lines](https://github.com/holaplex/kubes/blob/dev/validator/mainnet/deploy.yaml#L115-L117) by doing `kubectl edit deploy/validator -n mainnet-solana` 

from:
```yaml
        - name: accounts-storage
          emptyDir:
            medium: Memory
```
to
```yaml
- name: accounts-storage
   persistentVolumeClaim:
     claimName: accounts-storage-pvc
```
